language: julia

# Working around https://github.com/travis-ci/travis-ci/issues/4942
git:
  depth: 99999

before_install:
  - echo "$private_key"

julia:
  - 0.4
  - 0.5
  #- nightly

after_success:
    - julia -e 'Pkg.add("Documenter")'
    - julia -e 'Pkg.checkout("Documenter")'
    - julia docs/make.jl
